### ISSUE TITLE
Dialog closes instantly upon initialization

### ISSUE THREAD

**Issue by Janskiproducer** [HubSpot/vex#207] opened 2017-03-01 07:19 UTC
When trying to make Vex appear on the page, I first tested the initialization as a part of the jQuery document ready section. When the page loads, the dialog loads OK.

I then moved the opening of an alert out into it's own function, and tried to call that function from a href tag. The dialog loads, along with the overlay, but as soon as it's loaded it disappears again instantly. 

This is the function I call from the href:
function kjorpo(){
			vex.dialog.alert({
				message: 'This is a test',
				overlayClosesOnClick: false,
				showCloseButton: true
			});
		}

Tested in Chrome v. 56

**Comment by bbatliner** [comment] 2017-03-10 18:19
I'm assuming that when you say "call that function from a href tag" you mean, an anchor tag like this:

```html
<a href="#" onclick="kjorpo()">Link</a>
```

The problem is that clicking on the link triggers a `popstate` event - technically, the page is navigating to `#`. Vex detects this and by default closes all dialogs.

I would recommend using another element, like a `button`, and your code will work fine.

**Comment by bbatliner** [comment] 2018-02-24 19:25
You could also set the option `vex.defaultOptions.closeAllOnPopState` to `false` to disable that behavior... Closing to clean up!

**Closed by bbatliner** 2018-02-24 19:25 UTC

**Comment by aderegil** [comment] 2020-09-16 15:26
I am using Vuejs and ran into the same with

`<a href="#" v-on:click="confirmDelete(id)"></a>`

I cannot prevent the return, but @bbatliner suggestion solved the problem:

`vex.defaultOptions.closeAllOnPopState = false;`

Thanks.
