### ISSUE TITLE
Dialog closing flickers in IE

### ISSUE THREAD

**Issue by NoorKhan** [HubSpot/vex#126] opened 2015-06-22 17:29 UTC
So in IE 11 the dialog seems to flick when you close it. I tried looking into the source files a bit, but wasn't able to figure it out.

See here: http://jsfiddle.net/Yottabyte/ka7kutz2/5/

It doesn't do it every time, so keep clicking the "click" and you'll eventually see it. As it's fading out, it'll reappear in its completed state for a split second. It happens to me once every 4 tries or something. Sometimes it'll happen every time I do it.

**Comment by adamschwartz** [comment] 2015-06-22 17:58
Hey @NoorKhan thanks for reporting this. We’ll take a look.

**Comment by Fernando9** [comment] 2015-07-01 19:41
I am experiencing the same thing when  clicking away in  modal.  Only happens on IE11.  Other browsers  renders correctly.

**Comment by nerdyglasses** [comment] 2015-07-29 14:50
Unfortunately I experience the same thing.
My modal fades out but then shows up for half a second before the DOM element gets removed.

Any solution so far?

**Comment by adamschwartz** [comment] 2015-07-29 15:12
Unfortunately, I’m having trouble reproducing the issue in IE11.

Here’s [a video](https://slack-files.com/files-pub/T02999LMR-F08ATH42Y-a3b3294358/download/vex_ie_11_example.mov) of what I’m seeing when I open that jsFiddle.

Which specific version of IE11 are y’all running?

**Comment by nerdyglasses** [comment] 2015-07-29 16:27
here what I experience:
https://youtu.be/EP0nmVkXB1k

Here the IE Version
![screenshot 2015-07-29 18 23 11](https://cloud.githubusercontent.com/assets/449438/8963239/5f8631c0-361f-11e5-9248-b9150f1189fe.png)

**Comment by adamschwartz** [comment] 2015-07-29 16:41
Hey @nerdyglasses, thanks so much for sharing that. After a little searching, my best guess is that [this SO post](http://stackoverflow.com/questions/25086985/this-animation-flickers-at-the-end-in-ie-11) is the issue. If this is true then unfortunately this is a browser bug with the timing of the animation events, and working around it might be quite difficult. The [http://stackoverflow.com/a/26942573/131898](currently accepted solution) suggests using timeouts, but I’m not sure I’d be willing to go down that route since it may cause other issues.

I plan to report this as an issue to IE, and will report back with what I find. In the meantime, my best recommendation would be to workaround this by disabling certain animations with specific CSS for IE11. If you’d like more specific recommendations on how to accomplish this, I’d be happy to help. Just let me know.

**Comment by nerdyglasses** [comment] 2015-07-29 16:46
hey @adamschwartz! disabling those animations for IE would have been my strategy as well. 

you've to switch out title and url of the stackoverflow link :)

**Comment by adamschwartz** [comment] 2015-07-29 16:52
Thanks @nerdyglasses.

**Comment by gmoigneu** [comment] 2015-08-21 09:23
I don't know if the issue is related, but Chrome (46) seems to freeze the page after the close event for 3/4 seconds where you can't scroll. Clicking on the page after the load fix this. I haven't seen anything weird in the profiler. You can test that on the fiddle above.

**Comment by adamschwartz** [comment] 2015-12-11 20:09
It looks like the [IE issue I reported](https://connect.microsoft.com/IE/feedback/details/1605631/animation-end-events-firing-late) has now been effectively marked as “Won’t Fix”.

> This has now been fixed in the latest builds of Microsoft Edge. Unfortunately we are no longer working on IE feature bugs so that we can focus efforts on Microsoft Edge.
>
> All the best,
> The MS Edge Team

Fortunately, it looks like the issue _is_ fixed in Microsoft Edge. So _the future_ looks good for CSS animations in Edge, but the past will remain the past.

**Closed** 2015-12-11 20:10 UTC

**Comment by nerdyglasses** [comment] 2015-12-11 21:09
@adamschwartz thx
